import sqlite3
con = sqlite3.connect('EmployeeDatabase.db')
cursorObj = con.cursor()
cursorObj.execute("CREATE TABLE employees1(id INTEGER PRIMARY KEY, name text, salary integer, department text);")
cursorObj.execute("INSERT INTO employees1 VALUES(2, 'Adhyayan', 700, 'HR');")
data = [(3, 'Anjali', 800, 'Security'),(4, 'Ananya', 900, 'Managerial'),(5, 'Aakashdeep', 1000, 'DataScience')]
cursorObj.executemany("INSERT INTO employees1 VALUES(?,?,?,?)", data)
con.commit()
cursorObj.execute("Select * from employees1")
rows = cursorObj.fetchall()
for row in rows:
	print(row)
print("Enter the id of the employee you wanna display: ")
id = int(input())
cursorObj.execute("Select * from employees1 where id="+str(id)+";")
row = cursorObj.fetchall()
print(row)
print("Enter the id of the employee you wanna update: ")
id = int(input())
print("Enter the new Salary: ")
salary = int(input())
cursorObj.execute("Update employees1 SET salary = "+str(salary)+" where id ="+str(id)+";")
con.commit()
cursorObj.execute("Select * from employees1")
rows = cursorObj.fetchall()
for row in rows:
	print(row)
print("Enter id to delete: ")
id = int(input())
cursorObj.execute("Delete from employees1 where id ="+str(id)+";")
con.commit()
cursorObj.execute("Select * from employees1")
rows = cursorObj.fetchall()
for row in rows:
	print(row)
